"""Curriculum tree — lessons grouped by level.

Each lesson is a ``dict`` with ``title`` and ``path`` (absolute path to a
markdown file under ``content/``). The tutorial panel reads this directly;
the agent exposes ``list_tutorials`` / ``open_tutorial`` actions against it.
"""
from __future__ import annotations
from pathlib import Path
from typing import Dict, List, Any

_BASE = Path(__file__).parent / "content"


def _lesson(title: str, rel: str) -> Dict[str, Any]:
    return {"title": title, "path": _BASE / rel}


CURRICULUM: Dict[str, List[Dict[str, Any]]] = {
    "beginner": [
        _lesson("Welcome to organic chemistry",           "beginner/01_welcome.md"),
        _lesson("Atoms, bonds, hybridisation",            "beginner/02_atoms_bonds.md"),
        _lesson("Lewis & skeletal structures",            "beginner/03_structures.md"),
        _lesson("Functional groups overview",             "beginner/04_functional_groups.md"),
        _lesson("IUPAC nomenclature (introduction)",      "beginner/05_nomenclature.md"),
        _lesson("Acid–base chemistry & pKa",              "beginner/06_acid_base.md"),
        _lesson("Stereochemistry 101 — why 3D matters",   "beginner/07_stereochemistry_intro.md"),
        _lesson("Reading SMILES line notation",           "beginner/08_reading_smiles.md"),
        _lesson("Drawing organic molecules — skeletal conventions",
                "beginner/09_drawing_skeletal.md"),
        _lesson("Valence, formal charge & oxidation state",
                "beginner/10_valence_charge.md"),
        _lesson("Resonance & electron delocalization",
                "beginner/11_resonance.md"),
        _lesson("Polar bonds & electronegativity",
                "beginner/12_polar_bonds.md"),
        _lesson("Intermolecular forces",
                "beginner/13_intermolecular_forces.md"),
        _lesson("Solubility — \"like dissolves like\"",
                "beginner/14_solubility.md"),
        _lesson("Curly arrows — the mechanism alphabet",
                "beginner/15_curly_arrows.md"),
        _lesson("Nucleophiles vs electrophiles",
                "beginner/16_nucleophiles_electrophiles.md"),
        _lesson("Alkanes — the simplest hydrocarbons",
                "beginner/17_alkanes.md"),
        _lesson("Alkenes & alkynes",
                "beginner/18_alkenes_alkynes.md"),
        _lesson("Cycloalkanes — ring strain & chair conformations",
                "beginner/19_cycloalkanes.md"),
        _lesson("Aromaticity — what makes benzene special",
                "beginner/20_aromaticity_intro.md"),
        _lesson("Common organic solvents",
                "beginner/21_solvents.md"),
        _lesson("Reading ¹H NMR for the beginner",
                "beginner/22_nmr_qualitative.md"),
        _lesson("Reading IR spectra for the beginner",
                "beginner/23_ir_qualitative.md"),
        _lesson("Reading mass spectra for the beginner",
                "beginner/24_ms_qualitative.md"),
        _lesson("Lab safety basics",
                "beginner/25_lab_safety.md"),
        _lesson("Common glassware — touring the bench",
                "beginner/26_glassware.md"),
        _lesson("Recrystallisation for beginners",
                "beginner/27_recrystallisation_basics.md"),
        _lesson("TLC for beginners",
                "beginner/28_tlc_basics.md"),
        _lesson("Periodic trends — what to memorise + what to derive",
                "beginner/29_periodic_trends.md"),
        _lesson("Bond dissociation energies (BDEs)",
                "beginner/30_bond_dissociation_energy.md"),
        _lesson("Acids + bases — the three definitions",
                "beginner/31_acids_bases_definitions.md"),
        _lesson("The pKa table — what to memorise",
                "beginner/32_pka_table.md"),
        _lesson("Thermodynamics basics — ΔH, ΔS, ΔG",
                "beginner/33_thermodynamics_basics.md"),
        _lesson("Reaction kinetics intro — rate laws",
                "beginner/34_kinetics_intro.md"),
        _lesson("Activation energy + the Arrhenius equation",
                "beginner/35_activation_energy.md"),
        _lesson("Catalysis intro — what catalysts do",
                "beginner/36_catalysis_intro.md"),
        _lesson("Newman projections + butane conformations",
                "beginner/37_newman_projections.md"),
        _lesson("Common functional groups + their reactivity",
                "beginner/38_functional_group_reactivity.md"),
        _lesson("Equilibrium + Le Chatelier's principle",
                "beginner/39_equilibrium_le_chatelier.md"),
        _lesson("Hydrogen bonding — deeper",
                "beginner/40_hydrogen_bonding_deep.md"),
        _lesson("Aromatic, antiaromatic, and non-aromatic",
                "beginner/41_aromatic_antiaromatic.md"),
        _lesson("Inductive vs resonance effects on reactivity",
                "beginner/42_inductive_resonance_effects.md"),
        _lesson("The Hammond postulate",
                "beginner/43_hammond_postulate.md"),
        _lesson("Mass + moles + stoichiometry",
                "beginner/44_mass_moles_stoichiometry.md"),
        _lesson("Common reagent abbreviations",
                "beginner/45_reagent_abbreviations.md"),
        _lesson("Reading chemistry papers + ELN best practices",
                "beginner/46_reading_papers_eln.md"),
        _lesson("Common transformations cheat-sheet",
                "beginner/47_transformations_cheatsheet.md"),
        _lesson("Solvent selection — picking the right solvent",
                "beginner/48_solvent_selection.md"),
        _lesson("Concentration calculations — worked examples",
                "beginner/49_concentration_worked_examples.md"),
        _lesson("Aqueous chemistry intro",
                "beginner/50_aqueous_chemistry.md"),
        _lesson("Mole fraction + Raoult's law",
                "beginner/51_raoult_law.md"),
        _lesson("Vapour pressure + boiling point",
                "beginner/52_vapour_pressure_bp.md"),
        _lesson("Phase diagrams",
                "beginner/53_phase_diagrams.md"),
        _lesson("Polymer chemistry beginner intro",
                "beginner/54_polymer_intro.md"),
        _lesson("Tautomerism intro",
                "beginner/55_tautomerism.md"),
        _lesson("Acid-base titrations + indicators",
                "beginner/56_titration_indicators.md"),
        _lesson("Buffers + Henderson-Hasselbalch deeper",
                "beginner/57_buffers_deeper.md"),
        _lesson("Spectroscopy unit conversions",
                "beginner/58_spectroscopy_units.md"),
        _lesson("Electronic structure of atoms (Aufbau in detail)",
                "beginner/59_electronic_structure.md"),
        _lesson("Drawing 3D models (chairs, Newman, sawhorse)",
                "beginner/60_drawing_3d_models.md"),
        _lesson("Cis/trans + E/Z naming deeper",
                "beginner/61_cis_trans_ez.md"),
        _lesson("Naming bicyclic compounds",
                "beginner/62_naming_bicyclic.md"),
        _lesson("Naming heterocycles",
                "beginner/63_naming_heterocycles.md"),
        _lesson("Common organic synthons",
                "beginner/64_common_synthons.md"),
        _lesson("Functional group interconversions table",
                "beginner/65_fg_interconversions.md"),
        _lesson("Lab notebook templates",
                "beginner/66_lab_notebook_templates.md"),
        _lesson("Career paths in organic chemistry",
                "beginner/67_career_paths.md"),
        _lesson("Studying organic chemistry effectively",
                "beginner/68_studying_organic_chemistry.md"),
    ],
    "intermediate": [
        _lesson("Stereochemistry (R/S, E/Z, chirality)",  "intermediate/01_stereochemistry.md"),
        _lesson("Substitution (SN1 / SN2)",               "intermediate/02_substitution.md"),
        _lesson("Elimination (E1 / E2)",                  "intermediate/03_elimination.md"),
        _lesson("Aromaticity and electrophilic aromatic substitution", "intermediate/04_aromaticity.md"),
        _lesson("Carbonyl chemistry",                     "intermediate/05_carbonyl.md"),
        _lesson("Reaction energetics (profiles + kinetics)", "intermediate/06_energetics.md"),
        _lesson("Sugars and carbohydrates",               "intermediate/07_sugars.md"),
        _lesson("Radical reactions & chain mechanisms",   "intermediate/08_radicals.md"),
        _lesson("Polymer chemistry (step + chain growth)","intermediate/09_polymers.md"),
        _lesson("Protecting groups — orthogonal strategies","intermediate/10_protecting_groups.md"),
        _lesson("Isomerism — a unified hierarchy",          "intermediate/11_isomerism.md"),
        _lesson("Acyl substitution — the carbonyl ladder",
                "intermediate/12_acyl_substitution.md"),
        _lesson("Enolates + enolisation",
                "intermediate/13_enolates.md"),
        _lesson("Aldol + Claisen — the C–C bond formers",
                "intermediate/14_aldol_claisen_deep.md"),
        _lesson("Organometallic reagents (RLi, RMgX, R2CuLi)",
                "intermediate/15_organometallics.md"),
        _lesson("Redox in organic chemistry — methodology",
                "intermediate/16_redox_methodology.md"),
        _lesson("Amines — synthesis + reactivity",
                "intermediate/17_amines.md"),
        _lesson("Heterocycles — five + six-membered",
                "intermediate/18_heterocycles.md"),
        _lesson("Radicals deeper — chains, initiators, kinetics",
                "intermediate/19_radicals_deeper.md"),
        _lesson("Phase-transfer catalysis + ionic liquids",
                "intermediate/20_phase_transfer_ionic_liquids.md"),
        _lesson("Green chemistry — 12 principles + atom economy",
                "intermediate/21_green_chemistry.md"),
        _lesson("Carbohydrate chemistry — Fischer, Haworth, anomers",
                "intermediate/22_carbohydrate_chemistry.md"),
        _lesson("Amino acid + peptide chemistry",
                "intermediate/23_amino_acids_peptides.md"),
        _lesson("Lipid chemistry — fatty acids, glycerides, phospholipids",
                "intermediate/24_lipid_chemistry.md"),
        _lesson("Pericyclic reactions intro",
                "intermediate/25_pericyclic_intro.md"),
        _lesson("Reduction methods toolbox",
                "intermediate/26_reduction_methods.md"),
        _lesson("Oxidation methods toolbox",
                "intermediate/27_oxidation_methods.md"),
        _lesson("Alkene + alkyne addition reactions deeper",
                "intermediate/28_alkene_alkyne_addition.md"),
        _lesson("Carbocation chemistry deeper",
                "intermediate/29_carbocations_deep.md"),
        _lesson("Diazo + nitrene chemistry",
                "intermediate/30_diazo_nitrene.md"),
        _lesson("Steroids + terpenoids — biosynthesis + structure",
                "intermediate/31_steroids_terpenoids.md"),
        _lesson("Aldol condensation deeper",
                "intermediate/32_aldol_condensation_deeper.md"),
        _lesson("Olefination toolbox — Wittig, HWE, Julia, Peterson",
                "intermediate/33_olefination_toolbox.md"),
        _lesson("Friedel-Crafts deeper — alkylation + acylation",
                "intermediate/34_friedel_crafts_deep.md"),
        _lesson("Aromatic substitution patterns — DMG + ortho lithiation",
                "intermediate/35_aromatic_substitution_patterns.md"),
        _lesson("Oxime, hydrazone, imine chemistry",
                "intermediate/36_oxime_hydrazone_imine.md"),
        _lesson("Enol ether + dithiane chemistry (umpolung)",
                "intermediate/37_enol_ether_dithiane.md"),
        _lesson("The Ene reaction",
                "intermediate/38_ene_reaction.md"),
        _lesson("Sigmatropic rearrangements deeper",
                "intermediate/39_sigmatropic_deeper.md"),
        _lesson("Pinacol + semipinacol rearrangements",
                "intermediate/40_pinacol_semipinacol.md"),
        _lesson("Beckmann, Schmidt, Curtius rearrangements",
                "intermediate/41_beckmann_schmidt_curtius.md"),
        _lesson("Wolff rearrangement + Arndt-Eistert homologation",
                "intermediate/42_wolff_arndt_eistert.md"),
        _lesson("Mitsunobu reaction",
                "intermediate/43_mitsunobu.md"),
        _lesson("Appel reaction + similar OH-activation",
                "intermediate/44_appel_related.md"),
        _lesson("Reductive amination toolbox",
                "intermediate/45_reductive_amination_toolbox.md"),
        _lesson("Reformatsky reaction + zinc-enolate chemistry",
                "intermediate/46_reformatsky_etc.md"),
        _lesson("Mannich + heteroatom-Mannich variants",
                "intermediate/47_mannich_variants.md"),
        _lesson("Phosphine chemistry intro",
                "intermediate/48_phosphine_chemistry.md"),
        _lesson("Sulfur ylide (Corey-Chaykovsky) chemistry",
                "intermediate/49_sulfur_ylides.md"),
        _lesson("Boron chemistry intro",
                "intermediate/50_boron_chemistry.md"),
        _lesson("Silicon chemistry intro",
                "intermediate/51_silicon_chemistry.md"),
    ],
    "advanced": [
        _lesson("Pericyclic reactions",                   "advanced/01_pericyclic.md"),
        _lesson("Organometallic chemistry",               "advanced/02_organometallics.md"),
        _lesson("Retrosynthesis",                         "advanced/03_retrosynthesis.md"),
        _lesson("Spectroscopy (NMR / IR / MS)",           "advanced/04_spectroscopy.md"),
        _lesson("Green chemistry — case studies",         "advanced/05_green_chemistry.md"),
        _lesson("Flow & process chemistry",               "advanced/06_flow_process.md"),
        _lesson("Asymmetric organocatalysis",
                "advanced/07_asymmetric_organocatalysis.md"),
        _lesson("Pd cross-coupling deep-dive",
                "advanced/08_pd_cross_coupling_deep.md"),
        _lesson("C–H activation toolbox",
                "advanced/09_ch_activation.md"),
        _lesson("Olefin metathesis (Grubbs / Schrock)",
                "advanced/10_olefin_metathesis.md"),
        _lesson("Modern photoredox + EnT catalysis",
                "advanced/11_photochemistry_modern.md"),
        _lesson("Bioorthogonal chemistry",
                "advanced/12_bioorthogonal_chemistry.md"),
        _lesson("Macrocycle synthesis — escaping flatland",
                "advanced/13_macrocycles.md"),
        _lesson("Solid-phase synthesis (SPPS + DNA synthesis)",
                "advanced/14_solid_phase_synthesis.md"),
        _lesson("Combinatorial chemistry + DNA-encoded libraries",
                "advanced/15_combinatorial_del.md"),
        _lesson("Asymmetric hydrogenation",
                "advanced/16_asymmetric_hydrogenation.md"),
        _lesson("Total synthesis classics (Woodward, Corey, Nicolaou)",
                "advanced/17_total_synthesis_classics.md"),
        _lesson("Total synthesis modern (Baran, Stoltz, Sarpong)",
                "advanced/18_total_synthesis_modern.md"),
        _lesson("Catalytic asymmetric epoxidation",
                "advanced/19_asymmetric_epoxidation.md"),
        _lesson("Catalytic asymmetric dihydroxylation + AA",
                "advanced/20_asymmetric_dihydroxylation.md"),
        _lesson("Hydroformylation + carbonylation",
                "advanced/21_hydroformylation_carbonylation.md"),
        _lesson("Frustrated Lewis pairs",
                "advanced/22_frustrated_lewis_pairs.md"),
        _lesson("Single-atom catalysis",
                "advanced/23_single_atom_catalysis.md"),
        _lesson("Mechanochemistry — synthesis without solvent",
                "advanced/24_mechanochemistry.md"),
        _lesson("Sustainable polymer chemistry",
                "advanced/25_sustainable_polymers.md"),
        _lesson("Synthesis design tactics — a checklist",
                "advanced/26_synthesis_design_tactics.md"),
        _lesson("Ni-catalysed cross-coupling",
                "advanced/27_ni_cross_coupling.md"),
        _lesson("Cu chemistry — Ullmann, Glaser, Chan-Lam",
                "advanced/28_cu_chemistry.md"),
        _lesson("Au catalysis",
                "advanced/29_au_catalysis.md"),
        _lesson("Ru chemistry intro",
                "advanced/30_ru_chemistry.md"),
        _lesson("Ir-catalysed C-H borylation (Hartwig-Ishiyama)",
                "advanced/31_ir_borylation.md"),
        _lesson("Lithium chemistry deeper — DoM, halogen-metal exchange",
                "advanced/32_lithium_chemistry.md"),
        _lesson("Catalytic enantioselective C-H functionalisation",
                "advanced/33_asymmetric_ch_activation.md"),
        _lesson("Asymmetric phase-transfer catalysis (Maruoka)",
                "advanced/34_asymmetric_ptc.md"),
        _lesson("Enamine + iminium catalysis deeper",
                "advanced/35_enamine_iminium_deep.md"),
        _lesson("Hydrogen-bonding organocatalysis (Jacobsen thiourea)",
                "advanced/36_hbond_organocat.md"),
        _lesson("Brønsted-acid asymmetric catalysis (BINOL phosphates)",
                "advanced/37_binol_phosphate_catalysis.md"),
        _lesson("Allylation methods (Tsuji-Trost, Sakurai, Brown)",
                "advanced/38_allylation_methods.md"),
        _lesson("Aldol with chiral auxiliaries (Evans, Oppolzer)",
                "advanced/39_chiral_auxiliaries.md"),
        _lesson("Acylation + asymmetric acylation (Fu's nucleophilic cat)",
                "advanced/40_asymmetric_acylation.md"),
        _lesson("Cross-dehydrogenative coupling (CDC)",
                "advanced/41_cross_dehydrogenative_coupling.md"),
        _lesson("Functional group tolerance design",
                "advanced/42_fg_tolerance.md"),
        _lesson("Catalyst poisoning + sulfur tolerance",
                "advanced/43_catalyst_poisoning.md"),
        _lesson("Continuous-flow process design",
                "advanced/44_continuous_flow_design.md"),
        _lesson("Process safety in pharma",
                "advanced/45_process_safety.md"),
        _lesson("Cost of goods + green metrics for process",
                "advanced/46_cost_of_goods.md"),
    ],
    "graduate": [
        _lesson("Named reactions library",                "graduate/01_named_reactions.md"),
        _lesson("Asymmetric synthesis",                   "graduate/02_asymmetric.md"),
        _lesson("Molecular orbital theory & reactivity", "graduate/03_mo_theory.md"),
        _lesson("Case studies in total synthesis",        "graduate/04_total_synthesis.md"),
        _lesson("Catalysis — unified survey",             "graduate/05_catalysis.md"),
        _lesson("Biosynthesis & natural products",        "graduate/06_biosynthesis.md"),
        _lesson("Photoredox catalysis & visible-light chemistry",
                "graduate/07_photoredox.md"),
        _lesson("Click chemistry & bioconjugation",
                "graduate/08_click_chemistry.md"),
        _lesson("Enzyme catalysis essentials",
                "graduate/09_enzyme_catalysis.md"),
        _lesson("Computational chemistry & DFT essentials",
                "graduate/10_computational_chemistry.md"),
        _lesson("Wavefunction methods deeper (MP2, CCSD(T))",
                "graduate/11_wavefunction_methods.md"),
        _lesson("High-throughput experimentation + automation",
                "graduate/12_high_throughput_experimentation.md"),
        _lesson("Cheminformatics + ML for chemistry",
                "graduate/13_cheminformatics_ml.md"),
        _lesson("Drug discovery process — from target to IND",
                "graduate/14_drug_discovery_process.md"),
        _lesson("X-ray crystallography for chemists",
                "graduate/15_xray_crystallography.md"),
        _lesson("Cryo-EM — atomic resolution without crystals",
                "graduate/16_cryo_em.md"),
        _lesson("Controlled radical polymerisation (RAFT, ATRP, NMP)",
                "graduate/17_controlled_radical_polymerisation.md"),
        _lesson("MOFs + COFs — porous reticular frameworks",
                "graduate/18_mofs_cofs.md"),
        _lesson("Organic electrochemistry",
                "graduate/19_organic_electrochemistry.md"),
        _lesson("Flow chemistry — leaving the round-bottom flask",
                "graduate/20_flow_chemistry.md"),
        _lesson("NMR theory deeper — relaxation, NOE, 2D",
                "graduate/21_nmr_theory_deeper.md"),
        _lesson("Mass spectrometry deeper — analysers + IM-MS",
                "graduate/22_mass_spectrometry_deeper.md"),
        _lesson("Single-molecule + super-resolution microscopy",
                "graduate/23_single_molecule_super_resolution.md"),
        _lesson("Small-molecule crystallography (CSD, polymorphs)",
                "graduate/24_small_molecule_crystallography.md"),
        _lesson("Quantum mechanics primer for chemists",
                "graduate/25_qm_for_chemists.md"),
        _lesson("Molecular dynamics simulations",
                "graduate/26_molecular_dynamics.md"),
        _lesson("Free-energy methods (FEP, TI, umbrella sampling)",
                "graduate/27_free_energy_methods.md"),
        _lesson("Microbiome chemistry — gut metabolites + natural products",
                "graduate/28_microbiome_chemistry.md"),
        _lesson("Astrochemistry + prebiotic chemistry",
                "graduate/29_astrochemistry_prebiotic.md"),
        _lesson("Materials informatics — batteries, photovoltaics, catalysts",
                "graduate/30_materials_informatics.md"),
        _lesson("Solid-state NMR",
                "graduate/31_solid_state_nmr.md"),
        _lesson("Hyperpolarised NMR (DNP, PHIP, SABRE)",
                "graduate/32_hyperpolarised_nmr.md"),
        _lesson("EPR spectroscopy",
                "graduate/33_epr_spectroscopy.md"),
        _lesson("Mössbauer spectroscopy",
                "graduate/34_mossbauer.md"),
        _lesson("Photoelectron spectroscopy (XPS, UPS)",
                "graduate/35_xps_ups.md"),
        _lesson("Vibrational circular dichroism + chiroptical methods",
                "graduate/36_vcd.md"),
        _lesson("Absolute configuration determination",
                "graduate/37_absolute_config_determination.md"),
        _lesson("Computational catalyst design",
                "graduate/38_computational_catalyst_design.md"),
        _lesson("ML for retrosynthesis (AiZynth, ASKCOS, Synthia)",
                "graduate/39_ml_retrosynthesis.md"),
        _lesson("ML for protein design (RFdiffusion, ProteinMPNN)",
                "graduate/40_ml_protein_design.md"),
        _lesson("Neural network potentials deeper (MACE, NequIP)",
                "graduate/41_neural_network_potentials.md"),
        _lesson("Generative chemistry models (ChemBERTa, MolFormer, diffusion)",
                "graduate/42_generative_chemistry.md"),
        _lesson("Crystal structure prediction (CSP)",
                "graduate/43_crystal_structure_prediction.md"),
        _lesson("Free-energy methods for enzymes (EVB, QM/MM, MD-FEP)",
                "graduate/44_enzyme_free_energy.md"),
        _lesson("Molecular electronics",
                "graduate/45_molecular_electronics.md"),
        _lesson("Spintronic molecules + single-molecule magnets",
                "graduate/46_spintronic_molecules.md"),
        _lesson("OLEDs + emitter design",
                "graduate/47_oled_emitters.md"),
        _lesson("Battery electrolytes — chemistry frontiers",
                "graduate/48_battery_electrolytes.md"),
        _lesson("Hydrogen production + fuel cells",
                "graduate/49_hydrogen_fuel_cells.md"),
        _lesson("Carbon capture chemistry",
                "graduate/50_carbon_capture.md"),
    ],
}
